{application,tail_colors,
    [{compile_env,
         [{tail_colors,
              [colors],
              {ok,[<<"hawthorne">>,<<"burgandy">>,<<"silver-hawk">>]}},
          {tail_colors,
              [themed_colors],
              {ok,#{accent => <<"yellow">>,base => <<"slate">>,
                    error => <<"red">>,info => <<"sky">>,
                    primary => <<"purple">>,secondary => <<"blue">>,
                    success => <<"green">>,warning => <<"orange">>}}}]},
     {applications,[kernel,stdlib,elixir,logger]},
     {description,"tail_colors"},
     {modules,['Elixir.TailColors']},
     {registered,[]},
     {vsn,"0.1.0"}]}.
